# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev  # GHC
      - qt5-default  # ff-qt

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - >
    [ -x ~/.local/bin/stack ]
    || (travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
    | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack')
  - export STACK="stack --no-terminal --install-ghc"

matrix:
  include:
    - name: build and test
      install:
        # Build dependencies
        - $STACK build --test --only-dependencies
      script:
        # Build the package, its tests, and its docs and run the tests
        - test/script
    - name: hlint
      install:
        - $STACK build hlint
      script:
        - $STACK exec -- hlint .
    - name: haddock
      script:
        - $STACK haddock --no-haddock-deps
    - name: weeder
      install:
        - $STACK build weeder
      script:
        - $STACK exec -- weeder
  allow_failures:
    - name: weeder
